import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import fs from 'node:fs';
const bundle=await build({stdin:{contents:'export * from "./lib/domain.ts";export * from "./lib/catalog.ts";export * from "./lib/backend.ts";',resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,format:'esm',platform:'node'});
const {addExperience,applyAction,SPECIES,ITEMS,payload,farmAction}=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const user=(id,role='student')=>({id,loginId:id,name:id,role,mustChangePassword:false,passwordHash:'',authVersion:1,claimedStarter:false,pets:[],inventory:[]});
const act=(d,a,action,args={})=>applyAction(d,a,{action,requestId:crypto.randomUUID(),...args});
test('browser cannot invoke internal commit, replay or legacy gateway commands',async()=>{for(const action of ['commit','request','legacy','state','unsupported'])await assert.rejects(farmAction('fake-session',{action,requestId:crypto.randomUUID(),data:{pets:[],inventory:[]}}),/지원하지 않는 작업/);});
test('12 species, two per existing type, 36 distinct forms and all 40 assets exist',()=>{assert.equal(SPECIES.length,12);assert.equal(new Set(SPECIES.map(s=>s.id)).size,12);assert.deepEqual(Object.fromEntries(["잎","물","불","바람","흙","빛"].map(t=>[t,SPECIES.filter(s=>s.type===t).length])),{"잎":2,"물":2,"불":2,"바람":2,"흙":2,"빛":2});assert.equal(new Set(SPECIES.flatMap(s=>s.forms)).size,36);for(const s of SPECIES)for(let n=1;n<=3;n++)assert.ok(fs.statSync(`public/assets/pets/${s.id}-${n}.webp`).size>10000);assert.equal(ITEMS.length,4);for(const i of ITEMS)assert.ok(fs.existsSync(`public${i.image}`));});
test('growth evolves at 10/20, carries XP, caps at 30',()=>{assert.deepEqual(addExperience(9,110,30),{level:10,xp:20,stage:2});assert.deepEqual(addExperience(19,210,30),{level:20,xp:20,stage:3});assert.deepEqual(addExperience(29,300,240),{level:30,xp:0,stage:3});assert.throws(()=>addExperience(0,0,20));});
test('starter, ownership, three species, finite food and corrections',()=>{const d={className:'test',users:[user('t','teacher'),user('s'),user('other')]};act(d,'s','choosePet',{speciesId:'seedfox'});assert.throws(()=>act(d,'other','representative',{petId:d.users[1].pets[0].id}));act(d,'t','grant',{studentId:'s',sku:'pet-choice-ticket',quantity:3,reference:'ticket'});const ticket=d.users[1].inventory[0];for(const speciesId of ['bubblepenguin','glowmoth'])act(d,'s','choosePet',{speciesId,grantId:ticket.id});assert.throws(()=>act(d,'s','choosePet',{speciesId:'pebblemole',grantId:ticket.id}));assert.equal(ticket.remaining,1);assert.throws(()=>act(d,'s','grant',{studentId:'s',sku:'food-s',quantity:2,reference:'no'}));const pet=d.users[1].pets[1];act(d,'t','grant',{studentId:'s',sku:'food-s',quantity:2,reference:'food'});const food=d.users[1].inventory[1];act(d,'s','useItem',{petId:pet.id,grantId:food.id,quantity:2});assert.equal(pet.level,2);assert.equal(d.users[1].pets[0].level,1);assert.equal(food.remaining,0);assert.throws(()=>act(d,'s','useItem',{petId:pet.id,grantId:food.id,quantity:1}));});
test('same-origin JSON boundary rejects foreign origins and oversized requests',async()=>{await assert.rejects(payload(new Request('http://localhost/api/farm',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'})));await assert.rejects(payload(new Request('http://localhost/api/farm',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({x:'x'.repeat(17000)})})));assert.deepEqual(await payload(new Request('http://localhost/api/farm',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:'{"action":"logout"}'})),{action:'logout'});});

test('new species can be chosen and learn all skills through evolution',()=>{for(const species of SPECIES.slice(6)){const d={className:'test',users:[user('t','teacher'),user('s')]};act(d,'s','choosePet',{speciesId:species.id});const pet=d.users[1].pets[0];assert.equal(pet.speciesId,species.id);assert.deepEqual(pet.skills,[species.skills[0]]);assert.throws(()=>act(d,'s','choosePet',{speciesId:species.id}),/이미 키우고 있는 종/);for(const [level,stage] of [[10,2],[20,3]]){act(d,'t','adjustLevel',{studentId:'s',petId:pet.id,level,note:'진화 확인'});assert.equal(pet.stage,stage);assert.deepEqual(pet.skills,species.skills.slice(0,stage));}}});
