"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Native document links avoid vinext production RSC navigation failures. */
// Teacher accounts, admin approval, class creation and class settings (P2–P5).
import {useEffect,useState,type FormEvent,type ReactNode} from "react";

type RunResult={[k:string]:unknown};
export type Run=(a:string,d?:Record<string,unknown>)=>Promise<RunResult|false>;
type ClassOption={id:string;name:string};
type RoleRow={id?:string;name:string;capacity:number;salary:number;ruleKey?:string|null};
export type Preset={id:string;kind:"earn"|"spend";title:string;amount:number;all:boolean};

// Same-origin call for actions that return no farm state (class list, sign-up, admin).
export async function post(action:string,data:Record<string,unknown>={}){const r=await fetch("/api/farm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...data}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||"요청을 처리하지 못했어요.");return d;}
const errorText=(e:unknown)=>e instanceof Error?e.message:"요청을 처리하지 못했어요.";
const byName=new Intl.Collator("ko",{numeric:true}).compare;
const CLASS_KEY="petclass-class";
const remembered=()=>{try{return localStorage.getItem(CLASS_KEY)||"";}catch{return "";}};
const remember=(id:string)=>{try{localStorage.setItem(CLASS_KEY,id);}catch{/* private mode */}};
const toLocal=(iso?:string|null)=>iso?new Date(new Date(iso).getTime()-new Date(iso).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
const fromLocal=(v:string)=>v?new Date(v).toISOString():"";

export const DEFAULT_ROLES:RoleRow[]=[
 {name:"반장",capacity:2,salary:900,ruleKey:"leader"},{name:"지킴이",capacity:1,salary:600,ruleKey:"audit"},{name:"통장이",capacity:1,salary:550,ruleKey:"bank"},
 {name:"다독이",capacity:2,salary:350,ruleKey:"reading"},{name:"깔끔이",capacity:3,salary:400},{name:"칠판이",capacity:3,salary:500},{name:"가통이",capacity:4,salary:450},
 {name:"기록이",capacity:2,salary:350},{name:"디벗이",capacity:1,salary:350,ruleKey:"device"},{name:"알림이",capacity:2,salary:350},{name:"의견이",capacity:1,salary:350},
 {name:"체육반장",capacity:1,salary:300},{name:"출석이",capacity:2,salary:400}];
// Mirrors private.payroll_rules and the reading bonus; edit both together.
const COMMON_RULES="모든 역할 공통: 수행 수준 미달이면 월급 최대 30% 삭감, 2명 이상 역할은 공동 업무를 안 하면 월급 20%만 지급.";
const SPECIAL_RULES:Record<string,string[]>={
 leader:["친분에 따라 차별하면 누적 월급 90% 몰수","학급 관리 소홀·분위기 훼손이면 누적 월급 80% 몰수"],
 audit:["통장이의 기록 누락을 발견하지 못하면 그달 월급 0P","다음 달에 바로잡으면 월급 300P","2개월 연속 누락이면 월급 0P","통장이와 담합하면 누적 월급 전액 몰수"],
 bank:["포인트 기록 누락이면 월급 200P만 지급","명세서를 잃어버리면 월급 0P","지킴이와 담합하면 누적 월급 전액 몰수"],
 reading:["매달 추천 도서 권수만큼 추가 포인트: 2권까지 권당 100P, 3권부터 권당 50P, 최대 700P","포인트 대장에 '다독이 추천 도서' 탭이 생겨요","수행 미달인 달에는 추천 도서 추가금을 공제"],
 device:["디벗 보관함 비밀번호를 유출하면 누적 월급 50% 몰수"]};
function RuleBadge({open,toggle}:{open:boolean;toggle:()=>void}){return <button type="button" className="pc-rule-badge" aria-expanded={open} onClick={toggle}>특별 규칙 {open?"▲":"ⓘ"}</button>;}
function RuleInfo({ruleKey,name}:{ruleKey:string;name:string}){return <div className="pc-rule-info" role="note"><b>{name}의 특별 규칙</b><ul>{SPECIAL_RULES[ruleKey]?.map(t=><li key={t}>{t}</li>)}</ul><small>{COMMON_RULES} 월급 지급 때 포인트 대장의 “역할별 월급 조정”에서 체크해 적용해요.</small></div>;}
export function SpecialRoleNotice(){return <p className="pc-callout" role="note">특별한 규칙이 적용되는 역할 추가에 대해서는, 관리자(윤0후T)에게 문의하세요</p>;}

export function Login({run,busy,notice}:{run:Run;busy:boolean;notice:ReactNode}){
 const [mode,setMode]=useState<"student"|"teacher"|"signup">("student"),[classes,setClasses]=useState<ClassOption[]|null>(null),[classId,setClassId]=useState(""),[code,setCode]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[info,setInfo]=useState(""),[problem,setProblem]=useState("");
 useEffect(()=>{let live=true;post("classList").then(d=>{if(!live)return;const list=(d.classes as ClassOption[]).sort((a,b)=>byName(a.name,b.name));setClasses(list);const saved=remembered();setClassId(list.some(c=>c.id===saved)?saved:list.length===1?list[0].id:"");}).catch(e=>live&&setProblem(errorText(e)));return()=>{live=false;};},[]);
 const switchTo=(m:typeof mode)=>{setMode(m);setCode("");setPassword("");setInfo("");setProblem("");};
 const signup=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("password2"))return setProblem("비밀번호 확인이 달라요.");setProblem("");try{const d=await post("signup",{email:f.get("email"),password:f.get("password"),displayName:f.get("displayName"),className:f.get("className")});setMode("teacher");setEmail(String(f.get("email")));setPassword("");setInfo(String(d.message));}catch(err){setProblem(errorText(err));}};
 return <section className="pc-login-form"><span className="pc-eyebrow">반가워요, 농장지기</span><h2>{mode==="signup"?"선생님 가입 신청":"나의 친구를 만나러 가요"}</h2><p>{mode==="student"?"우리 반을 고르고 나의 고유 번호를 입력해요.":mode==="teacher"?"선생님 계정 이메일로 로그인해요.":"관리자가 승인하면 학급을 만들 수 있어요. 학생 이름은 저장하지 않아요."}</p>
 {mode!=="signup"&&<div className="pc-segment"><button aria-pressed={mode==="student"} onClick={()=>switchTo("student")}>학생</button><button aria-pressed={mode==="teacher"} onClick={()=>switchTo("teacher")}>선생님</button></div>}
 {mode==="student"&&<form onSubmit={async e=>{e.preventDefault();remember(classId);await run("login",{classId,code});}}><label>우리 반<select className="pc-plain" required value={classId} onChange={e=>setClassId(e.target.value)}><option value="" disabled>{classes===null?"반 목록을 불러오는 중…":"반을 골라 주세요"}</option>{classes?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>나의 고유 번호<input type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" maxLength={4} minLength={4} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="4자리 숫자"/></label><button className="pc-primary" disabled={busy||!classId}>{busy?"확인하는 중…":"입장하기 →"}</button></form>}
 {mode==="teacher"&&<form onSubmit={async e=>{e.preventDefault();await run("teacherLogin",{email,password});}}><label>이메일<input className="pc-plain" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>비밀번호<input className="pc-plain" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="pc-primary" disabled={busy}>{busy?"확인하는 중…":"로그인 →"}</button><button type="button" className="pc-text" onClick={()=>switchTo("signup")}>처음이신가요? 선생님 가입 신청 →</button><small className="pc-subtle">비밀번호를 잊었다면 관리자(윤0후T)에게 문의하세요.</small></form>}
 {mode==="signup"&&<form onSubmit={signup}><label>이메일 (로그인 아이디)<input className="pc-plain" name="email" type="email" autoComplete="username" required maxLength={254}/></label><label>비밀번호 (8자 이상)<input className="pc-plain" name="password" type="password" autoComplete="new-password" required minLength={8} maxLength={72}/></label><label>비밀번호 확인<input className="pc-plain" name="password2" type="password" autoComplete="new-password" required minLength={8} maxLength={72}/></label><label>이름 (화면 표시용)<input className="pc-plain" name="displayName" required maxLength={30} placeholder="예: 윤○○"/></label><label>반 이름<input className="pc-plain" name="className" required maxLength={20} placeholder="예: 2학년 1반, 개멋진반"/></label><p className="pc-subtle">반 이름은 학생 로그인 화면 목록에 보여요. 다른 반과 겹치면 안 돼요.</p><button className="pc-primary">가입 신청 →</button><button type="button" className="pc-text" onClick={()=>switchTo("teacher")}>← 로그인으로 돌아가기</button></form>}
 {info&&<div className="pc-notice" role="status">✓ {info}</div>}{problem&&<div className="pc-notice pc-error" role="alert">{problem}</div>}{notice}<small>공용 기기에서는 사용 후 꼭 학생 전환을 눌러 주세요.</small></section>;
}

function RoleTable({rows,setRows,count}:{rows:RoleRow[];setRows:(r:RoleRow[])=>void;count:number}){const [info,setInfo]=useState<string|null>(null);const set=(i:number,k:keyof RoleRow,v:string|number)=>setRows(rows.map((r,j)=>j===i?{...r,[k]:v}:r));const total=rows.reduce((n,r)=>n+(Number(r.capacity)||0),0);
 return <><div className="pc-role-rows"><div className="pc-role-head"><span>역할</span><span>정원</span><span>월급(P)</span><span/></div>{rows.map((r,i)=><div key={i}><span className="pc-role-name"><input aria-label={`역할 ${i+1} 이름`} value={r.name} maxLength={20} required disabled={!!r.ruleKey} onChange={e=>set(i,"name",e.target.value)}/>{r.ruleKey&&<RuleBadge open={info===r.ruleKey} toggle={()=>setInfo(info===r.ruleKey?null:r.ruleKey!)}/>}</span><input aria-label={`${r.name} 정원`} type="number" min={1} max={40} required value={r.capacity} onChange={e=>set(i,"capacity",Number(e.target.value))}/><input aria-label={`${r.name} 월급`} type="number" min={0} max={10000} required value={r.salary} onChange={e=>set(i,"salary",Number(e.target.value))}/><button type="button" className="pc-danger" onClick={()=>setRows(rows.filter((_,j)=>j!==i))}>빼기</button>{r.ruleKey&&info===r.ruleKey&&<RuleInfo ruleKey={r.ruleKey} name={r.name}/>}</div>)}</div>
 <button type="button" className="pc-text" disabled={rows.length>=30} onClick={()=>setRows([...rows,{name:"",capacity:1,salary:300}])}>+ 일반 역할 추가</button><p className={total===count?"pc-calculation":"pc-calculation pc-warn"}>정원 합계 <b>{total} / 학생 {count}명</b>{total!==count&&" · 합계가 학생 수와 달라요(저장은 돼요)"}</p><SpecialRoleNotice/></>;}

export function ClassWizard({suggested,run,busy,notice,logout}:{suggested:string;run:Run;busy:boolean;notice:ReactNode;logout:()=>void}){const [rows,setRows]=useState<RoleRow[]>(DEFAULT_ROLES),[count,setCount]=useState(25),[name,setName]=useState(suggested),[deadline,setDeadline]=useState("");
 return <main className="petclass pc-setup"><div className="pc-setup-head"><a className="pc-logo" href="/">✳ PetClass</a><button className="pc-text" disabled={busy} onClick={logout}>로그아웃</button></div><span className="pc-eyebrow">승인 완료 · 처음 한 번만</span><h1>우리 반 만들기</h1><p className="pc-subtle">학생 번호(1~{count}번)와 개인 4자리 번호, 테스트 학생(0번), 펫 상점·미니게임 기본값이 함께 만들어져요. 모든 값은 나중에 학급 관리에서 바꿀 수 있어요.</p>{notice}
 <form className="pc-panel" onSubmit={async e=>{e.preventDefault();await run("classCreate",{name,studentCount:count,deadline:fromLocal(deadline),roles:rows});}}><label>반 이름<input required maxLength={20} value={name} onChange={e=>setName(e.target.value)} placeholder="예: 1학년 3반"/></label><label>학생 수<input type="number" min={1} max={40} required value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>역할 신청 마감<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><h2>1인 1역 역할</h2><p className="pc-subtle">지금 운영 중인 13개 역할이 기본이에요. 빼거나 정원·월급을 바꾸고 일반 역할을 더할 수 있어요. <b>특별 규칙</b>을 누르면 어떤 규칙인지 보여요.</p><RoleTable rows={rows} setRows={setRows} count={count}/><button className="pc-primary" disabled={busy}>{busy?"만드는 중…":"이대로 학급 만들기 →"}</button></form></main>;}

export function PasswordForm({run}:{run:Run}){return <form className="pc-panel" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(f.get("next")!==f.get("next2"))return void window.alert("새 비밀번호 확인이 달라요.");if(await run("changePassword",{current:f.get("current"),next:f.get("next")}))form.reset();}}><h2>내 계정 비밀번호 변경</h2><label>현재 비밀번호<input name="current" type="password" autoComplete="current-password" required/></label><label>새 비밀번호 (8자 이상)<input name="next" type="password" autoComplete="new-password" required minLength={8} maxLength={72}/></label><label>새 비밀번호 확인<input name="next2" type="password" autoComplete="new-password" required minLength={8} maxLength={72}/></label><button className="pc-primary">비밀번호 변경</button></form>;}

type ClassInfo={className?:string;studentCount?:number;settings:{deadline:string};roles:(RoleRow&{id:string})[];students:{roleId:string|null}[];presets:Preset[]};
// Teacher-side class settings shown in 학급 관리.
export function ClassSettings({data,run,done}:{data:ClassInfo;run:Run;done:()=>Promise<unknown>}){
 const act=async(a:string,d:Record<string,unknown>)=>{if(await run(a,d))await done();};
 const [rows,setRows]=useState(data.roles),[presets,setPresets]=useState(data.presets),[info,setInfo]=useState<string|null>(null);
 // Server data replaces local edits after every save.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setRows(data.roles);setPresets(data.presets);},[data.roles,data.presets]);
 const set=(i:number,k:string,v:string|number)=>setRows(rows.map((r,j)=>j===i?{...r,[k]:v}:r));
 const setP=(i:number,k:string,v:string|number|boolean)=>setPresets(presets.map((r,j)=>j===i?{...r,[k]:v}:r));
 const move=(i:number,d:number)=>{const ids=rows.map(r=>r.id);[ids[i],ids[i+d]]=[ids[i+d],ids[i]];void act("roleOrder",{ids});};
 const total=rows.reduce((n,r)=>n+(Number(r.capacity)||0),0),count=data.studentCount??data.students.length;
 return <>
 <form className="pc-panel" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const n=Number(f.get("count"));if(n<count&&!window.confirm(`학생 수를 ${count}명에서 ${n}명으로 줄일까요?\n${n+1}번부터는 로그인할 수 없게 되고 역할이 해제돼요. 포인트·펫 기록은 남아요.`))return;await act("classUpdate",{name:f.get("name"),studentCount:n,deadline:fromLocal(String(f.get("deadline")))});}}><h2>학급 정보</h2><label>반 이름<input name="name" required maxLength={20} defaultValue={data.className} key={data.className}/></label><label>학생 수<input name="count" type="number" min={1} max={40} required defaultValue={count} key={count}/></label><label>역할 신청 마감<input name="deadline" type="datetime-local" defaultValue={toLocal(data.settings.deadline)} key={data.settings.deadline}/></label><p className="pc-subtle">학생 수를 줄이면 뒷번호부터 비활성(기록 보존), 다시 늘리면 같은 번호로 돌아와요.</p><button className="pc-primary">학급 정보 저장</button></form>
 <section className="pc-panel"><h2>역할 편집</h2><p className="pc-subtle">정원 합계 <b>{total} / 학생 {count}명</b>. 특별 규칙 역할은 이름을 바꿀 수 없어요. <b>특별 규칙</b>을 누르면 내용이 보여요.</p><div className="pc-role-rows pc-role-edit"><div className="pc-role-head"><span>역할</span><span>정원</span><span>월급(P)</span><span>배정</span><span/></div>{rows.map((r,i)=><div key={r.id}><span className="pc-role-name"><input aria-label={`${r.name} 이름`} value={r.name} maxLength={20} disabled={!!r.ruleKey} onChange={e=>set(i,"name",e.target.value)}/>{r.ruleKey&&<RuleBadge open={info===r.ruleKey} toggle={()=>setInfo(info===r.ruleKey?null:r.ruleKey!)}/>}</span><input aria-label={`${r.name} 정원`} type="number" min={1} max={40} value={r.capacity} onChange={e=>set(i,"capacity",Number(e.target.value))}/><input aria-label={`${r.name} 월급`} type="number" min={0} max={10000} value={r.salary} onChange={e=>set(i,"salary",Number(e.target.value))}/><small>{data.students.filter(s=>s.roleId===r.id).length}명</small><span className="pc-row-actions"><button type="button" aria-label={`${r.name} 위로`} disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button type="button" aria-label={`${r.name} 아래로`} disabled={i===rows.length-1} onClick={()=>move(i,1)}>↓</button><button type="button" onClick={()=>void act("roleSave",{id:r.id,name:r.name,capacity:String(r.capacity),salary:String(r.salary)})}>저장</button><button type="button" className="pc-danger" onClick={()=>{if(window.confirm(`'${r.name}' 역할을 삭제할까요?\n배정된 학생은 미배정이 되고, 이 역할 지원 기록도 사라져요.`))void act("roleDelete",{id:r.id});}}>삭제</button></span>{r.ruleKey&&info===r.ruleKey&&<RuleInfo ruleKey={r.ruleKey} name={r.name}/>}</div>)}</div>
 <form className="pc-inline-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await run("roleSave",{name:f.get("name"),capacity:String(f.get("capacity")),salary:String(f.get("salary"))})){form.reset();await done();}}}><input name="name" aria-label="새 역할 이름" required maxLength={20} placeholder="새 일반 역할 이름"/><input name="capacity" aria-label="새 역할 정원" type="number" min={1} max={40} required defaultValue={1}/><input name="salary" aria-label="새 역할 월급" type="number" min={0} max={10000} required defaultValue={300}/><button className="pc-primary">+ 역할 추가</button></form><SpecialRoleNotice/></section>
 <section className="pc-panel"><h2>포인트 지급·차감 사유</h2><p className="pc-subtle">포인트 대장에서 고르는 항목이에요. 금액 0은 직접 입력.</p><div className="pc-role-rows pc-preset-edit">{presets.map((p,i)=><div key={p.id}><select aria-label="종류" value={p.kind} onChange={e=>setP(i,"kind",e.target.value)}><option value="earn">지급</option><option value="spend">차감</option></select><input aria-label="사유" value={p.title} maxLength={40} onChange={e=>setP(i,"title",e.target.value)}/><input aria-label="금액" type="number" min={0} max={100000} value={p.amount} onChange={e=>setP(i,"amount",Number(e.target.value))}/><label className="pc-check"><input type="checkbox" checked={p.all} onChange={e=>setP(i,"all",e.target.checked)}/>전체</label><span className="pc-row-actions"><button type="button" onClick={()=>void act("presetSave",{id:p.id,kind:p.kind,title:p.title,amount:String(p.amount),all:p.all})}>저장</button><button type="button" className="pc-danger" onClick={()=>{if(window.confirm(`'${p.title}' 사유를 삭제할까요?`))void act("presetDelete",{id:p.id});}}>삭제</button></span></div>)}</div>
 <form className="pc-inline-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await run("presetSave",{kind:f.get("kind"),title:f.get("title"),amount:String(f.get("amount")||0),all:f.get("all")==="on"})){form.reset();await done();}}}><select name="kind" aria-label="새 사유 종류"><option value="earn">지급</option><option value="spend">차감</option></select><input name="title" aria-label="새 사유" required maxLength={40} placeholder="새 사유"/><input name="amount" aria-label="새 사유 금액" type="number" min={0} max={100000} defaultValue={0}/><label className="pc-check"><input type="checkbox" name="all"/>전체</label><button className="pc-primary">+ 사유 추가</button></form></section></>;}

type AccountRow={id:string;email:string;displayName:string;status:"pending"|"approved"|"rejected";requestedClassName:string|null;note:string|null;createdAt:string;className:string|null;studentCount:number|null};
export function AdminPanel({name,run,logout}:{name:string;run:Run;logout:()=>void}){
 const [accounts,setAccounts]=useState<AccountRow[]|null>(null),[info,setInfo]=useState(""),[problem,setProblem]=useState(""),[working,setWorking]=useState(false);
 const call=async(action:string,data:Record<string,unknown>={})=>{setWorking(true);setProblem("");setInfo("");try{const d=await post(action,data);if(d.accounts)setAccounts(d.accounts);if(d.message)setInfo(d.message);return d;}catch(e){setProblem(errorText(e));return null;}finally{setWorking(false);}};
 // Loads once; later updates come back with each admin action.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void call("adminList");},[]);
 const download=async(a:AccountRow)=>{const d=await call("adminExport",{id:a.id});if(!d)return;const url=URL.createObjectURL(new Blob([JSON.stringify(d.export,null,1)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`${(a.className||a.email).replace(/\s+/g,"_")}_백업_${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);};
 const groups:[string,AccountRow["status"]][]=[["승인 대기","pending"],["승인됨","approved"],["거절됨","rejected"]];
 return <main className="petclass pc-setup"><div className="pc-setup-head"><a className="pc-logo" href="/">✳ PetClass</a><span>{name} 계정<button className="pc-text" onClick={logout}>로그아웃</button></span></div><span className="pc-eyebrow">관리자 전용</span><h1>선생님 계정 관리</h1><p className="pc-subtle">관리자는 계정 승인·거절, 임시 비밀번호, 학급 데이터 초기화, 계정 삭제만 할 수 있어요. 학급 안의 데이터는 보이지 않아요.</p>
 {info&&<div className="pc-notice" role="status">✓ {info}</div>}{problem&&<div className="pc-notice pc-error" role="alert">{problem}</div>}
 {accounts===null?<p className="pc-subtle">불러오는 중…</p>:groups.map(([title,status])=>{const list=accounts.filter(a=>a.status===status);return <section className="pc-panel" key={status}><h2>{title} <small>{list.length}명</small></h2>{!list.length&&<p className="pc-subtle">없어요.</p>}{list.map(a=><article className="pc-account" key={a.id}><header><div><b>{a.displayName||"(이름 없음)"}</b><span>{a.email}</span></div><div><b>{a.className||a.requestedClassName||"반 이름 없음"}</b><span>{a.className?`학생 ${a.studentCount}명`:"학급 만들기 전"} · 가입 {new Date(a.createdAt).toLocaleDateString("ko-KR")}</span></div></header>{a.note&&<p className="pc-subtle">거절 사유: {a.note}</p>}
  {status!=="approved"&&<form className="pc-inline-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await call("adminReview",{id:a.id,approve:(e.nativeEvent as SubmitEvent).submitter?.getAttribute("value")==="approve",note:f.get("note")});}}><input name="note" aria-label="거절 사유" maxLength={200} placeholder="거절 사유 (선택)"/><button className="pc-primary" value="approve" disabled={working}>승인</button><button className="pc-danger" value="reject" disabled={working||status==="rejected"}>거절</button></form>}
  {status==="approved"&&<details><summary>계정 관리</summary><form className="pc-inline-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await call("adminSetPassword",{id:a.id,password:new FormData(form).get("password")}))form.reset();}}><input name="password" aria-label="임시 비밀번호" required minLength={8} maxLength={72} placeholder="임시 비밀번호 (8자 이상)"/><button className="pc-primary" disabled={working}>임시 비밀번호 지정</button></form><p className="pc-subtle">임시 비밀번호를 선생님께 직접 알려 주세요. 로그인 후 학급 관리에서 바꿀 수 있어요.</p>
   <div className="pc-danger-zone"><p><b>되돌릴 수 없는 작업</b> · 먼저 백업을 내려받으세요.</p>{a.className&&<button className="pc-text" disabled={working} onClick={()=>void download(a)}>학급 데이터 JSON 내려받기</button>}<form className="pc-inline-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,confirm=new FormData(form).get("confirm"),act=(e.nativeEvent as SubmitEvent).submitter?.getAttribute("value");const label=act==="adminResetClass"?"학급 데이터(포인트·펫·역할 배정·구매·게임·기록)를 비울까요? 계정·학급 설정·학생 번호는 남아요.":"계정과 학급의 모든 데이터를 삭제할까요?";if(act&&window.confirm(label)&&await call(act,{id:a.id,confirm}))form.reset();}}><input name="confirm" aria-label="확인 문구" required placeholder={`확인: ${a.className||a.email} 입력`}/>{a.className&&<button className="pc-danger" value="adminResetClass" disabled={working}>학급 데이터 초기화</button>}<button className="pc-danger" value="adminDeleteAccount" disabled={working}>계정 삭제</button></form></div></details>}
 </article>)}</section>;})}
 <PasswordForm run={run}/></main>;
}
