"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Native document links avoid vinext production RSC navigation failures. */
import Image from "next/image";
import {useCallback,useEffect,useRef,useState,type ReactNode} from "react";
import {SPECIES,allItems,evolutionName,getItem,getSpecies,imageFor,isArchived,nextLevelXp,addExperience,registerProducts} from "@/lib/catalog";
import type {FarmState,Student,Pet,Grant} from "@/lib/types";
import {Apply,Ledger,LedgerRows,Manage,RoleBoard,Roles,useClassroom} from "./classroom";
import "./petclass.css";

type Product={sku:string;name:string;price:number;description:string;kind:string;xp?:number;archived?:boolean;image?:string|null};
type Entry={id:string;studentNo:number;delta:number;title:string;detail:string;createdAt:string};
type Order={id:string;student_id:string;student_no:number;sku:string;quantity:number;unit_price:number;refunded_quantity:number;created_at:string};
type State=Omit<FarmState,"students"> & {balance:number;version:number;claimedStarter:boolean;products:Product[];ledger:Entry[];orders:Order[];updatedAt:string;students:(Student&{balance:number;studentNo:number})[]};
type Tab="farm"|"shop"|"inventory"|"dex"|"records"|"teacher"|"roles"|"ledger"|"apply"|"manage";
type Modal={kind:"choose"}|{kind:"buy";sku:string}|{kind:"feed";petId?:string;sku?:string}|{kind:"student";id:string}|{kind:"refund";order:Order}|{kind:"addProduct";category:string}|null;
const money=(v:number)=>v.toLocaleString("ko-KR")+"P";
const date=(v:string)=>new Date(v).toLocaleString("ko-KR",{timeZone:"Asia/Seoul",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
const title:Record<Tab,string>={farm:"나의 작은 친구들",shop:"포인트 상점",inventory:"아이템 보관함",dex:"친구 도감",records:"나의 활동 기록",teacher:"우리 반 성장 이야기",roles:"학생 역할 배정",ledger:"포인트 대장",apply:"내 역할 신청",manage:"학급 관리"};
const count=(grants:Grant[],sku:string)=>grants.filter(g=>g.sku===sku&&!g.revoked).reduce((n,g)=>n+g.remaining,0);
function Art({id,stage=1,priority=false}:{id:string;stage?:number;priority?:boolean}){return <Image className="pc-art" src={`/assets/pets/${id}-${stage}.webp`} alt={evolutionName(id,stage)} width={512} height={512} unoptimized priority={priority}/>;}
function ItemArt({sku}:{sku:string}){const src=imageFor(sku);return src?<Image className="pc-item-art" src={src} width={256} height={256} alt="" unoptimized/>:<span className="pc-reward-icon" aria-hidden>✦</span>;}
function Progress({pet}:{pet:Pet}){const max=nextLevelXp(pet.level);return <div className="pc-progress"><div><b>Lv.{pet.level}</b><span>{max?`${pet.xp} / ${max} XP`:"최고 레벨"}</span></div><progress aria-label={`${evolutionName(pet.speciesId,pet.stage)} 경험치`} max={max||1} value={max?pet.xp:1}/><small>{pet.stage===3?"최종 진화 완료":`다음 진화 Lv.${pet.stage===1?10:20}`}</small></div>;}
function Dialog({title,close,children}:{title:string;close:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{old?.focus();};},[]);return <dialog className="pc-dialog" ref={ref} aria-labelledby="pc-dialog-title" onCancel={e=>{e.preventDefault();close();}}><div className="pc-dialog-head"><h2 id="pc-dialog-title">{title}</h2><button type="button" aria-label="닫기" onClick={close}>×</button></div>{children}</dialog>;}
export default function Home(){
 const [state,setState]=useState<State|null>(null),[tab,setTab]=useState<Tab>("farm"),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[modal,setModal]=useState<Modal>(null),[loginRole,setLoginRole]=useState("student"),[code,setCode]=useState(""),[search,setSearch]=useState("");
 const classroom=useClassroom(state?.user?.role??null,setMessage);
 const working=useRef(false),retry=useRef(new Map<string,string>()),sequence=useRef(0),identity=useRef<string|null>(null);
 const refresh=useCallback(async()=>{if(working.current)return;const v=++sequence.current;try{const r=await fetch("/api/farm",{cache:"no-store",signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw Error(d.error);if(v!==sequence.current)return;if(identity.current!==(d.state.user?.id||null)){setModal(null);setMessage("");retry.current.clear();}identity.current=d.state.user?.id||null;registerProducts(d.state.products);setState(d.state);setError("");}catch(e){if(v===sequence.current)setError(e instanceof Error?e.message:"연결에 실패했어요.");}},[]);
 // State updates happen after the awaited network response.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void refresh();const focus=()=>{if(!document.hidden)void refresh();};window.addEventListener("focus",focus);document.addEventListener("visibilitychange",focus);return()=>{window.removeEventListener("focus",focus);document.removeEventListener("visibilitychange",focus);};},[refresh]);
 async function run(action:string,data:Record<string,unknown>={}){if(working.current)return false;working.current=true;sequence.current++;setBusy(true);setError("");setMessage("");const key=JSON.stringify({action,...data});const requestId=retry.current.get(key)||crypto.randomUUID();retry.current.set(key,requestId);
  try{const r=await fetch("/api/farm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,requestId,...data}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok){if(r.status===401){setState(old=>old?{...old,user:null,pets:[],inventory:[],students:[],ledger:[],orders:[],logs:[],balance:0}:old);setCode("");setModal(null);identity.current=null;retry.current.clear();}throw Error(d.error||"요청을 처리하지 못했어요.");}identity.current=d.state.user?.id||null;registerProducts(d.state.products);setState(d.state);setMessage(d.message||"");retry.current.delete(key);if(action==="points")void classroom.refresh();if(action==="login"){setModal(null);retry.current.clear();setCode("");setTab(d.state.user.role==="teacher"?"teacher":"farm");}if(action==="logout"){retry.current.clear();setCode("");setTab("farm");setModal(null);}return true;}catch(e){setError(e instanceof Error?e.message:"연결이 끊겼어요. 같은 작업을 다시 누르면 처리 결과를 확인합니다.");return false;}finally{working.current=false;setBusy(false);}}
 const notice=<>{error&&<div className="pc-notice pc-error" role="alert">{error}<button disabled={busy} onClick={()=>void refresh()}>다시 불러오기</button></div>}{message&&<div className="pc-notice" role="status">✓ {message}</div>}</>;
 if(!state)return <main className="petclass pc-loading"><div className="pc-logo">✳ PetClass</div><h1>{error?"잠시 연결을 확인해 주세요":"우리 반 친구들을 만나러 가요"}</h1>{error?<>{notice}<p>입력한 작업의 처리 여부를 먼저 확인해 주세요.</p></>:<p>학급 정보를 불러오는 중…</p>}</main>;
 const teacher=state.user?.role==="teacher";const activeTab=teacher&&tab==="farm"?"teacher":tab;
 if(!state.user&&tab!=="dex")return <main className="petclass pc-login"><section className="pc-login-art"><a className="pc-logo" href="/">✳ PetClass</a><div className="pc-login-copy"><span className="pc-eyebrow">작은 노력, 커다란 성장</span><h1>우리 반에서<br/>시작하는<br/><em>특별한 우정.</em></h1><p>모은 포인트로 돌보고,<br/>함께 자라며 새로운 모습을 만나요.</p></div><div className="pc-login-pets"><Art id="seedfox" priority/><Art id="bubblepenguin"/></div><span className="pc-stamp">6가지 친구 · 18가지 모습</span></section><section className="pc-login-form"><span className="pc-eyebrow">반가워요, 농장지기</span><h2>나의 친구를 만나러 가요</h2><p>기존 학급 사이트의 번호를 그대로 사용해요.</p><div className="pc-segment"><button aria-pressed={loginRole==="student"} onClick={()=>{setLoginRole("student");setCode("");}}>학생</button><button aria-pressed={loginRole==="teacher"} onClick={()=>{setLoginRole("teacher");setCode("");}}>선생님</button></div><form onSubmit={async e=>{e.preventDefault();await run("login",{role:loginRole,code});}}><label>{loginRole==="teacher"?"교사 비밀번호":"나의 고유 번호"}<input type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" maxLength={4} minLength={4} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="4자리 숫자"/></label><button className="pc-primary" disabled={busy}>{busy?"확인하는 중…":"입장하기 →"}</button></form>{notice}<button className="pc-text" onClick={()=>setTab("dex")}>로그인 없이 친구 도감 둘러보기 ↗</button><small>공용 기기에서는 사용 후 꼭 학생 전환을 눌러 주세요.</small></section></main>;
 const tabs:Tab[]=!state.user?["dex"]:teacher?["teacher","roles","ledger","shop","dex","records","manage"]:["farm","shop","inventory","dex","records","apply"];
 const cls=classroom.data,refreshAll=async()=>{await classroom.refresh();await refresh();},open=(t:Tab)=>{setTab(t);setError("");setMessage("");};
 const featured=state.pets.find(p=>p.representative)||state.pets[0];
 return <div className="petclass pc-shell"><a className="pc-skip" href="#pc-main">본문 바로가기</a><aside className="pc-sidebar"><a className="pc-logo" href="/">✳ PetClass</a><div className="pc-class"><span>함께 자라는 교실</span><b>{state.className}</b></div><nav aria-label="주 메뉴">{tabs.map(t=><button key={t} aria-current={activeTab===t?"page":undefined} onClick={()=>{setTab(t);setError("");setMessage("");}}><span aria-hidden>{({farm:"⌂",teacher:"⌂",shop:"◈",inventory:"▣",dex:"❋",records:"◷",roles:"♙",ledger:"₩",apply:"✎",manage:"⚙"})[t]}</span>{({teacher:"우리 반",farm:"내 펫",shop:"상점",inventory:"보관함",dex:"도감",records:"기록",roles:"학생 역할",ledger:"포인트 대장",apply:"역할 신청",manage:"학급 관리"})[t]}</button>)}</nav><div className="pc-sidebar-bottom"><p>성장에는 저마다의<br/><b>속도가 있어요.</b></p><div><strong>{state.user?.name||"둘러보는 중"}</strong><button disabled={busy} onClick={()=>state.user?void run("logout"):setTab("farm")}>{state.user?(teacher?"교사 모드 잠그기":"학생 전환 / 나가기"):"로그인"}</button></div></div></aside><div className="pc-workspace"><header className="pc-top"><span>{teacher?"TEACHER’S GARDEN":"MY LITTLE WORLD"}</span><div>{!teacher&&state.user&&<b className="pc-wallet">✦ {money(state.balance)}</b>}<button aria-label="최신 상태 불러오기" disabled={busy} onClick={()=>{void refresh();void classroom.refresh();}}>↻</button><small>{state.updatedAt&&date(state.updatedAt)} 갱신</small></div></header><main id="pc-main"><div className="pc-heading"><div><span className="pc-eyebrow">{teacher?"함께 돌보는 우리 반":"오늘도 한 뼘 더 자라는"}</span><h1>{title[activeTab]}</h1></div>{activeTab==="farm"&&<span>{state.pets.length} / 3 마리</span>}</div>{!modal&&notice}
 {activeTab==="farm"&&<><section className="pc-habitat"><div><span className="pc-pill">{featured?"MY DEAR FRIEND":"OUR FIRST HELLO"}</span><h2>{featured?<>오늘도 너와 함께,<br/><em>{evolutionName(featured.speciesId,featured.stage)}.</em></>:<>우리의 첫 만남,<br/><em>어떤 친구일까요?</em></>}</h2><p>{featured?getSpecies(featured.speciesId)?.description:"여섯 친구 중 마음에 드는 한 마리를 무료로 맞이해요."}</p><button className="pc-primary" onClick={()=>setModal(featured?{kind:"feed",petId:featured.id}:{kind:"choose"})}>{featured?"이 친구에게 먹이 주기":"첫 펫 무료로 선택하기"} →</button></div><div className="pc-habitat-art"><Art id={featured?.speciesId||"seedfox"} stage={featured?.stage||1} priority/>{featured&&<span className="pc-pet-label">{getSpecies(featured.speciesId)?.type} · Lv.{featured.level}</span>}</div></section><div className="pc-section-head"><h2>함께하는 나의 펫</h2><button className="pc-text" onClick={()=>setTab("dex")}>진화 모습 둘러보기 ↗</button></div><div className="pc-pet-grid">{state.pets.map(p=><article className="pc-pet-card" key={p.id}><div className="pc-card-top"><span className="pc-pill">{getSpecies(p.speciesId)?.type}</span>{p.representative&&<small>✦ 대표 펫</small>}</div><Art id={p.speciesId} stage={p.stage}/><h3>{evolutionName(p.speciesId,p.stage)}</h3><Progress pet={p}/><button className="pc-primary" onClick={()=>setModal({kind:"feed",petId:p.id})}>먹이 주기</button>{!p.representative&&<button className="pc-text" disabled={busy} onClick={()=>void run("representative",{petId:p.id})}>대표 펫으로 선택</button>}</article>)}{state.pets.length<3&&<button className="pc-empty-card" onClick={()=>!state.pets.length||count(state.inventory,"pet-choice-ticket")?setModal({kind:"choose"}):setTab("shop")}><span>+</span><h3>새 친구를 위한 자리</h3><p>{!state.pets.length?"첫 번째 친구는 무료예요":count(state.inventory,"pet-choice-ticket")?"보유한 초대권으로 만나기":"상점에서 새 친구 초대권을 구해요"}</p></button>}</div>{cls&&<RoleBoard data={cls} action="역할 신청" onAction={()=>open("apply")}/>}</>}
 {activeTab==="shop"&&<Shop state={state} teacher={teacher} busy={busy} buy={sku=>setModal({kind:"buy",sku})} add={category=>setModal({kind:"addProduct",category})} run={run}/>}
 {activeTab==="inventory"&&<><p className="pc-subtle">구매한 아이템이 바로 도착해요. 같은 아이템은 한곳에 모았어요.</p><div className="pc-item-grid">{allItems().map(i=>{const n=count(state.inventory,i.sku);return n>0&&<article className="pc-item-card" key={i.sku}><ItemArt sku={i.sku}/><span className="pc-pill">× {n}개</span><h3>{i.name}</h3><p>{i.description}</p><button disabled={!state.pets.length||(i.kind==="ticket"&&state.pets.length>=3)} className="pc-primary" onClick={()=>setModal(i.kind==="ticket"?{kind:"choose"}:{kind:"feed",sku:i.sku})}>{!state.pets.length?"첫 펫을 먼저 선택해 주세요":i.kind==="ticket"?"새 친구 만나기":"먹이 주기"}</button></article>;})}</div>{!state.inventory.some(g=>!g.revoked&&g.remaining>0)&&<div className="pc-empty"><h2>친구를 위한 첫 선물</h2><p>모은 포인트로 상점에서 성장 음식을 골라 보세요.</p><button className="pc-primary" onClick={()=>setTab("shop")}>상점으로 가기 →</button></div>}</>}
 {activeTab==="dex"&&<Dex/>}
 {["roles","ledger","apply","manage"].includes(activeTab)&&(cls?<div className="pc-legacy">{activeTab==="roles"&&<Roles data={cls} token="session" refresh={refreshAll} say={setMessage}/>}{activeTab==="ledger"&&<Ledger data={cls} token="session" refresh={refreshAll} say={setMessage}/>}{activeTab==="apply"&&<Apply data={cls} refresh={refreshAll} say={setMessage}/>}{activeTab==="manage"&&<Manage data={cls} token="session" refresh={refreshAll} say={setMessage}/>}</div>:<p className="pc-subtle">학급 정보를 불러오는 중…</p>)}
 {activeTab==="teacher"&&<><div className="pc-summary"><div><span>우리 반 학생</span><b>{state.students.length}<small>명</small></b></div><div><span>함께하는 펫</span><b>{state.students.reduce((n,s)=>n+s.pets.length,0)}<small>마리</small></b></div><div><span>첫 만남을 기다리는 학생</span><b>{state.students.filter(s=>!s.pets.length).length}<small>명</small></b></div>{cls&&<><div><span>역할 배정</span><b>{cls.students.filter(s=>s.roleId).length}<small>/ 25</small></b><p>정원 내 지원은 자동 배정</p></div><div><span>역할 지원</span><b>{Object.values(cls.applicationCounts).reduce((a,b)=>a+b,0)}<small>건</small></b><p>접수된 지원서</p></div><div><span>누적 포인트</span><b>{cls.ledger.reduce((n,e)=>n+e.delta,0).toLocaleString("ko-KR")}<small>P</small></b><p>급여 · 보너스 · 상점 자동 반영</p></div></>}</div><Points students={state.students} busy={busy} run={run}/>{cls&&<><RoleBoard data={cls} action="역할 배정" onAction={()=>open("roles")}/><section className="pc-panel"><div className="pc-panel-head"><div><h2>최근 포인트 기록</h2><p className="pc-subtle">급여·지급·사용 기록은 한 대장에 쌓여요.</p></div><button className="pc-text" onClick={()=>open("ledger")}>대장 열기 →</button></div><div className="pc-legacy"><LedgerRows rows={cls.ledger} limit={5}/></div></section></>}<div className="pc-section-head"><h2>학생별 성장 현황</h2><input aria-label="학생 번호 검색" placeholder="학생 번호 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="pc-roster">{state.students.filter(s=>!search||String(s.studentNo).includes(search)).map(s=><button className="pc-student" key={s.id} onClick={()=>setModal({kind:"student",id:s.id})}><div><b>{s.name}</b><span>{money(s.balance)}</span></div><div className="pc-mini-pets">{s.pets.length?s.pets.map(p=><div key={p.id}><Art id={p.speciesId} stage={p.stage}/><small>Lv.{p.level}</small></div>):<span>아직 첫 펫 선택 전</span>}</div><small>상세 · 지급 · 성장 정정 ↗</small></button>)}</div></>}
 {activeTab==="records"&&<><section className="pc-panel"><h2>{teacher?"구매·환불 내역":"내 구매 내역"}</h2><div className="pc-records">{state.orders.map(o=><div key={o.id}><div><b>{teacher&&`${o.student_no}번 · `}{state.products.find(i=>i.sku===o.sku)?.name||o.sku} ×{o.quantity}</b><small>{date(o.created_at)} · 주문 {o.id.slice(0,8)}</small></div><span>{money(o.unit_price*o.quantity)}{o.refunded_quantity>0&&<small>{o.refunded_quantity}개 환불됨</small>}</span>{teacher&&getItem(o.sku)&&!o.refunded_quantity&&<button onClick={()=>setModal({kind:"refund",order:o})}>미사용분 환불</button>}</div>)}{!state.orders.length&&<p>아직 구매 내역이 없어요.</p>}</div></section><section className="pc-panel"><h2>{teacher?"학급 포인트 기록":"내 포인트 기록"}</h2><p className="pc-subtle">본인과 선생님만 상세 내역을 볼 수 있어요. 최근 300건.</p><div className="pc-records">{state.ledger.map(e=><div key={e.id}><div><b>{teacher&&`${e.studentNo}번 · `}{e.title}</b><small>{date(e.createdAt)} · {e.detail}</small></div><strong className={e.delta>0?"pc-positive":""}>{e.delta>0?"+":""}{money(e.delta)}</strong></div>)}</div></section><section className="pc-panel"><h2>펫 활동</h2>{state.logs.map(l=><div className="pc-log" key={l.id}><span>{l.message}</span><small>{date(l.createdAt)}</small></div>)}</section></>}
 </main></div>{modal&&<Dialog title={modal.kind==="choose"?"평생 함께할 친구 고르기":modal.kind==="buy"?"구매 내용 확인":modal.kind==="feed"?"친구에게 먹이 주기":modal.kind==="refund"?"미사용 아이템 환불":modal.kind==="addProduct"?(modal.category==="pet"?"펫 용품 추가":"학급 보상 추가"):"학생 상세"} close={()=>{if(!busy){setModal(null);setError("");}}}>{notice}{modal.kind==="addProduct"&&<AddProduct category={modal.category} busy={busy} run={run} done={()=>setModal(null)}/>}{modal.kind==="choose"&&<Choose state={state} busy={busy} run={run} done={()=>setModal(null)}/>} {modal.kind==="buy"&&<Purchase state={state} product={state.products.find(p=>p.sku===modal.sku)!} busy={busy} run={run} done={()=>{setModal(null);setTab(state.products.find(p=>p.sku===modal.sku)?.kind==="classroom"?"records":"inventory");}}/>}{modal.kind==="feed"&&<Feed state={state} initialPet={modal.petId} initialSku={modal.sku} busy={busy} run={run} done={()=>setModal(null)} shop={()=>{setModal(null);setTab("shop");}}/>}{modal.kind==="student"&&<StudentPanel student={state.students.find(s=>s.id===modal.id)!} busy={busy} run={run}/>} {modal.kind==="refund"&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run("refund",{orderId:modal.order.id,note:f.get("note")}))setModal(null);}}><p>남아 있는 미사용 수량만 구매 당시 가격으로 환불합니다. 이미 사용한 아이템은 환불하지 않아요.</p><label>환불 사유<input name="note" required minLength={2} maxLength={80}/></label><button className="pc-primary" disabled={busy}>미사용분 회수하고 포인트 반환</button></form>}</Dialog>}</div>;
}

type Run=(a:string,d?:Record<string,unknown>)=>Promise<boolean>;
function Dex(){return <><div className="pc-dex-intro"><span>6가지 친구, 18가지 성장 이야기</span><h2>작은 시작,<br/>놀라운 세 번의 변화.</h2><p>Lv.1 → Lv.10 → Lv.20 · 모습도 이름도 함께 자라나요.</p><b>18</b></div>{SPECIES.map((s,index)=><section className="pc-dex-species" key={s.id}><span className="pc-eyebrow">NO. {String(index+1).padStart(2,"0")} · {s.type}</span><h2>{s.forms[0]}의 성장 이야기</h2><p>{s.description}</p><div className="pc-evolutions">{s.forms.map((name,i)=><article key={name}><Art id={s.id} stage={i+1}/><small>{i===0?"처음 만난 모습 · Lv.1":`${i+1}단계 진화 · Lv.${i===1?10:20}`}</small><h3>{name}</h3><p>✦ {s.skills[i]}</p><small>해당 레벨에 자동 습득</small></article>)}</div></section>)}</>;}
function Choose({state,busy,run,done}:{state:State;busy:boolean;run:Run;done:()=>void}){const [selected,setSelected]=useState("");return <><p>{state.pets.length?"초대권 1장 사용 · 같은 종 중복 없이 최대 3마리":"첫 친구는 무료예요. 마음에 드는 친구를 골라 주세요."}</p><div className="pc-chooser">{SPECIES.map(s=><button key={s.id} aria-pressed={selected===s.id} disabled={busy||state.pets.some(p=>p.speciesId===s.id)} onClick={()=>setSelected(s.id)}><Art id={s.id}/><b>{s.forms[0]}</b><small>{s.type} · {state.pets.some(p=>p.speciesId===s.id)?"함께하는 중":"선택 가능"}</small></button>)}</div><p className="pc-subtle">선택한 종은 바꿀 수 없어요. 도감에서 최종 진화 모습도 확인해 보세요.</p><button className="pc-primary" disabled={!selected||busy} onClick={async()=>{if(await run("choosePet",{speciesId:selected}))done();}}>{selected?`${getSpecies(selected)?.forms[0]}와 함께 시작하기`:"친구를 선택해 주세요"}</button></>;}
function Shop({state,teacher,busy,buy,add,run}:{state:State;teacher:boolean;busy:boolean;buy:(s:string)=>void;add:(category:string)=>void;run:Run}){const [category,setCategory]=useState("pet");const visible=state.products.filter(p=>!p.archived);const list=visible.filter(p=>(p.kind==="classroom")===(category==="classroom"));
 const move=(i:number,d:number)=>{const skus=visible.map(p=>p.sku),a=skus.indexOf(list[i].sku),b=skus.indexOf(list[i+d].sku);[skus[a],skus[b]]=[skus[b],skus[a]];void run("reorderProducts",{skus});};
 const remove=(p:Product)=>{if(window.confirm(`'${p.name}' 상품을 삭제할까요?\n학생 상점에서 사라지고 되돌릴 수 없어요. 이미 산 아이템과 구매 기록은 그대로 남아요.`))void run("removeProduct",{sku:p.sku});};
 return <><div className="pc-shop-banner"><div><span className="pc-eyebrow">작은 노력에 보내는 선물</span><h2>모은 포인트로<br/>함께 자라는 즐거움.</h2><p>{teacher?"상품 가격·추가·삭제·순서를 관리할 수 있어요.":"펫 용품은 구매 즉시 보관함에 도착해요."}</p></div><ItemArt sku="food-l"/></div><div className="pc-segment"><button aria-pressed={category==="pet"} onClick={()=>setCategory("pet")}>펫 용품</button><button aria-pressed={category==="classroom"} onClick={()=>setCategory("classroom")}>학급 보상</button></div><div className="pc-item-grid">{list.map((p,i)=>{const ticket=p.kind==="ticket"&&(!state.pets.length||state.pets.length+count(state.inventory,p.sku)>=3);return <article className="pc-item-card" key={p.sku}><ItemArt sku={p.sku}/><h3>{p.name}</h3><p>{p.description}</p><b className="pc-price">{money(p.price)}</b>{teacher?<><form className="pc-price-form" key={p.price} onSubmit={async e=>{e.preventDefault();await run("price",{sku:p.sku,price:Number(new FormData(e.currentTarget).get("price"))});}}><input aria-label={`${p.name} 가격`} name="price" type="number" min={1} max={100000} defaultValue={p.price} required/><button disabled={busy}>저장</button></form><div className="pc-shop-admin"><button aria-label={`${p.name} 앞으로 옮기기`} disabled={busy||i===0} onClick={()=>move(i,-1)}>←</button><button aria-label={`${p.name} 뒤로 옮기기`} disabled={busy||i===list.length-1} onClick={()=>move(i,1)}>→</button><button className="pc-danger" disabled={busy} onClick={()=>remove(p)}>삭제</button></div></>:<button className="pc-primary" disabled={busy||ticket||state.balance<p.price} onClick={()=>buy(p.sku)}>{ticket?(!state.pets.length?"첫 무료 펫을 먼저 선택해요":"초대 가능한 자리가 없어요"):state.balance<p.price?`${money(p.price-state.balance)} 더 필요해요`:"구매하기"}</button>}</article>;})}{teacher&&<button className="pc-empty-card" onClick={()=>add(category)}><span>+</span><h3>상품 추가</h3><p>{category==="pet"?"펫 용품":"학급 보상"}을 새로 만들어요</p></button>}</div></>;}
// Shrink uploads so they fit the DB column and the request limit.
async function shrink(file:File){const bmp=await createImageBitmap(file);const k=Math.min(1,384/Math.max(bmp.width,bmp.height));const c=document.createElement("canvas");c.width=Math.round(bmp.width*k);c.height=Math.round(bmp.height*k);c.getContext("2d")!.drawImage(bmp,0,0,c.width,c.height);let url=c.toDataURL("image/webp",.85);if(!url.startsWith("data:image/webp")||url.length>350000)url=c.toDataURL("image/png");if(url.length>350000)url=c.toDataURL("image/jpeg",.85);return url;}
function AddProduct({category,busy,run,done}:{category:string;busy:boolean;run:Run;done:()=>void}){const [image,setImage]=useState(""),[problem,setProblem]=useState("");return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run("addProduct",{category,name:f.get("name"),description:f.get("description"),price:Number(f.get("price")),...(category==="pet"?{xp:Number(f.get("xp"))}:{}),...(image?{image}:{})}))done();}}><p className="pc-subtle">{category==="pet"?"펫 용품은 사면 보관함에 들어가고, 먹이로 주면 경험치가 올라요.":"학급 보상은 구매 기록을 선생님이 확인해요."}</p><label>이름<input name="name" required maxLength={40}/></label><label>설명<input name="description" maxLength={80}/></label><label>포인트<input name="price" type="number" min={1} max={100000} required/></label>{category==="pet"&&<label>경험치<input name="xp" type="number" min={1} max={10000} required/></label>}<label>이미지<input type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];setImage("");setProblem("");if(file)try{setImage(await shrink(file));}catch{setProblem("이미지를 읽지 못했어요. 다른 파일을 골라 주세요.");}}}/></label>{image&&<Image className="pc-add-preview" src={image} width={160} height={160} alt="추가할 이미지 미리보기" unoptimized/>}{problem&&<p role="alert">{problem}</p>}<button className="pc-primary" disabled={busy}>{busy?"추가하는 중…":"상품 추가"}</button></form>;}
function Purchase({state,product,busy,run,done}:{state:State;product:Product;busy:boolean;run:Run;done:()=>void}){const [qty,setQty]=useState(1);const total=qty*product.price;return <form onSubmit={async e=>{e.preventDefault();if(await run("purchase",{sku:product.sku,quantity:qty,expectedPrice:product.price}))done();}}><div className="pc-purchase-preview"><ItemArt sku={product.sku}/><h3>{product.name}</h3></div><label>수량<input type="number" min={1} max={product.kind==="ticket"||product.sku==="seat"?1:99} value={qty} onChange={e=>setQty(Number(e.target.value))} required/></label><div className="pc-calculation"><p>현재 잔액 <b>{money(state.balance)}</b></p><p>사용 포인트 <b>−{money(total)}</b></p><p>구매 후 잔액 <b>{money(state.balance-total)}</b></p></div><p>{product.kind==="classroom"?"구매 기록은 선생님이 확인할 수 있어요.":"구매 즉시 보관함에 지급돼요."}</p><button className="pc-primary" disabled={busy||total>state.balance||qty<1}>{busy?"구매 처리 중…":`${money(total)} 사용하고 구매`}</button></form>;}
function Feed({state,initialPet,initialSku,busy,run,done,shop}:{state:State;initialPet?:string;initialSku?:string;busy:boolean;run:Run;done:()=>void;shop:()=>void}){const foods=allItems().filter(i=>i.kind==="food"&&count(state.inventory,i.sku)>0);const [petId,setPet]=useState(initialPet||state.pets.find(p=>p.representative)?.id||state.pets[0]?.id||"");const [sku,setSku]=useState(initialSku||foods[0]?.sku||"");const [qty,setQty]=useState(1);const p=state.pets.find(p=>p.id===petId);const item=getItem(sku);const valid=p&&item&&qty>=1&&Number.isInteger(qty)&&qty<=count(state.inventory,sku)&&p.level<30&&!(qty>1&&addExperience(p.level,p.xp,(qty-1)*(item.xp||0)).level>=30);const preview=valid?addExperience(p.level,p.xp,qty*(item.xp||0)):null;if(!foods.length)return <div className="pc-empty"><h3>성장 음식이 필요해요</h3><p>상점에서 포인트로 음식을 구매할 수 있어요.</p><button className="pc-primary" onClick={shop}>상점으로 가기 →</button></div>;return <form onSubmit={async e=>{e.preventDefault();if(valid&&await run("useItem",{petId,sku,quantity:qty}))done();}}>{p&&<div className="pc-feed-pet"><Art id={p.speciesId} stage={p.stage}/><Progress pet={p}/></div>}<label>먹이를 받을 친구<select value={petId} onChange={e=>setPet(e.target.value)}>{state.pets.map(p=><option key={p.id} value={p.id}>{evolutionName(p.speciesId,p.stage)} · Lv.{p.level}</option>)}</select></label><label>성장 음식<select value={sku} onChange={e=>{setSku(e.target.value);setQty(1);}}>{foods.map(i=><option key={i.sku} value={i.sku}>{i.name} · {count(state.inventory,i.sku)}개 보유 · XP +{i.xp}</option>)}</select></label><label>사용 수량<input type="number" min={1} max={count(state.inventory,sku)} value={qty} onChange={e=>setQty(Number(e.target.value))} required/></label>{preview?<div className="pc-calculation"><b>Lv.{p!.level} → Lv.{preview.level}</b>{preview.stage>p!.stage&&<p>✦ {evolutionName(p!.speciesId,preview.stage)}로 진화해요!</p>}{preview.level===30&&<p>최고 레벨 이후 남는 경험치는 저장되지 않아요.</p>}</div>:<p role="status">최고 레벨 또는 보유 수량을 확인해 주세요. 남을 음식은 사용하지 않아요.</p>}<button className="pc-primary" disabled={busy||!valid}>{p?`${evolutionName(p.speciesId,p.stage)}에게 ${qty}개 주기`:"친구를 선택해 주세요"}</button></form>;}
function Points({students,busy,run}:{students:State["students"];busy:boolean;run:Run}){const [ids,setIds]=useState<string[]>([]),[delta,setDelta]=useState(60),[reason,setReason]=useState("학급 내 선행"),[confirm,setConfirm]=useState(false);return <section className="pc-panel"><h2>포인트 빠른 지급·차감</h2><form onSubmit={async e=>{e.preventDefault();if(!confirm){setConfirm(true);return;}if(await run("points",{studentIds:ids,delta,title:reason})){setIds([]);setConfirm(false);}}}><div className="pc-student-select">{students.map(s=><label key={s.id}><input type="checkbox" checked={ids.includes(s.id)} onChange={e=>{setConfirm(false);setIds(old=>e.target.checked?[...old,s.id]:old.filter(id=>id!==s.id));}}/>{s.studentNo}번</label>)}</div><button type="button" className="pc-text" onClick={()=>{setIds(ids.length===students.length?[]:students.map(s=>s.id));setConfirm(false);}}>전체 선택 / 해제</button><div className="pc-form-row"><label>포인트 · 차감은 음수<input type="number" value={delta} min={-100000} max={100000} onChange={e=>{setDelta(Number(e.target.value));setConfirm(false);}} required/></label><label>사유<input value={reason} maxLength={40} onChange={e=>{setReason(e.target.value);setConfirm(false);}} required/></label></div>{confirm&&<p className="pc-calculation">선택한 {ids.length}명에게 각각 <b>{money(delta)}</b> 기록합니다.</p>}<button className="pc-primary" disabled={busy||!ids.length||!delta}>{confirm?"확인 · 포인트 기록":`${ids.length}명 선택 · 내용 확인`}</button></form></section>;}
function StudentPanel({student,busy,run}:{student:State["students"][number];busy:boolean;run:Run}){return <><h3>{student.name} · {money(student.balance)}</h3><div className="pc-student-pets">{student.pets.map(p=><article key={p.id}><Art id={p.speciesId} stage={p.stage}/><h3>{evolutionName(p.speciesId,p.stage)}</h3><Progress pet={p}/><details><summary>성장 레벨 정정</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run("adjustLevel",{studentId:student.id,petId:p.id,level:Number(f.get("level")),note:f.get("note")});}}><label>레벨<input name="level" type="number" min={1} max={30} defaultValue={p.level} required/></label><label>사유<input name="note" minLength={2} maxLength={80} required/></label><p>정정 시 경험치는 0으로 변경됩니다.</p><button className="pc-primary" disabled={busy}>정정 적용</button></form></details></article>)}</div><h3>특별 보상 지급</h3><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run("grant",{studentId:student.id,sku:f.get("sku"),quantity:Number(f.get("quantity")),note:f.get("note")});}}><label>아이템<select name="sku">{allItems().filter(i=>!isArchived(i.sku)).map(i=><option key={i.sku} value={i.sku}>{i.name}</option>)}</select></label><label>수량<input name="quantity" type="number" defaultValue={1} min={1} max={99} required/></label><label>지급 사유<input name="note" required minLength={2} maxLength={80}/></label><p className="pc-subtle">포인트 차감 없는 교사 특별 지급입니다.</p><button className="pc-primary" disabled={busy}>보관함으로 지급</button></form></>;}
