-- Generated by `supabase migration new mock_battles_tournaments`; ordered after P2.
create table private.petclass_battles (
 id uuid primary key, class_id uuid not null references private.classes on delete cascade,
 challenger uuid not null, opponent uuid not null,
 status text not null default 'pending' check(status in ('pending','accepted','rejected','active','finished')),
 data jsonb not null default '{}', version int not null default 0,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(challenger<>opponent),
 foreign key(class_id,challenger) references public.classroom_students(class_id,id) on delete cascade,
 foreign key(class_id,opponent) references public.classroom_students(class_id,id) on delete cascade
);
create index petclass_battles_class on private.petclass_battles(class_id,updated_at desc);
create unique index petclass_battles_open_pair on private.petclass_battles(least(challenger,opponent),greatest(challenger,opponent)) where status in ('pending','accepted','active');
create table private.petclass_tournaments (
 id uuid primary key, class_id uuid not null references private.classes on delete cascade,
 name text not null check(char_length(name) between 1 and 80),
 conditions text not null check(char_length(conditions)<=2000),
 pet_limit int not null check(pet_limit between 1 and 3),
 prize text not null check(char_length(prize) between 1 and 1000),
 created_at timestamptz not null default now()
);
create table private.petclass_battle_requests (
 actor_id text not null, request_id uuid not null, fingerprint text not null,
 battle_id uuid not null references private.petclass_battles on delete cascade,
 primary key(actor_id,request_id)
);
alter table private.petclass_battles enable row level security;
alter table private.petclass_tournaments enable row level security;
alter table private.petclass_battle_requests enable row level security;

create function private.pc_battle_lobby(a jsonb) returns jsonb language sql stable set search_path='' as $$
 select jsonb_build_object(
  'user',a-'teacherToken',
  'students',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'no',s.student_no,'hasPets',coalesce(jsonb_array_length(f.data->'pets'),0)>0) order by s.student_no)
    from public.classroom_students s left join private.petclass_farms f on f.student_id=s.id where s.class_id=(a->>'classId')::uuid and s.active),'[]'),
  'battles',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'challenger',b.challenger,'opponent',b.opponent,'status',b.status,'version',b.version,'createdAt',b.created_at,
    'data',(b.data-'choices')||jsonb_build_object('ready',jsonb_build_array(coalesce(b.data->'choices'->0<>'null'::jsonb,false),coalesce(b.data->'choices'->1<>'null'::jsonb,false)))) order by b.created_at desc)
    from private.petclass_battles b where b.class_id=(a->>'classId')::uuid and a->>'role'='student' and (a->>'id' in(b.challenger::text,b.opponent::text))),'[]'),
  'tournaments',coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'conditions',t.conditions,'petLimit',t.pet_limit,'prize',t.prize,'createdAt',t.created_at) order by t.created_at desc)
    from private.petclass_tournaments t where t.class_id=(a->>'classId')::uuid),'[]')
 );
$$;

alter function public.petclass_gateway(text,text,text,jsonb) rename to pc_before_battles;
alter function public.pc_before_battles(text,text,text,jsonb) set schema private;
create function public.petclass_gateway(p_key text,p_action text,p_token text,p_body jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare a jsonb;cls uuid;sid uuid;bid uuid;b private.petclass_battles;r private.petclass_battle_requests;target uuid;existing private.petclass_tournaments;
begin
 if p_action not in('battleLobby','battleChallenge','battleRespond','battleContext','battleCommit','tournamentCreate') then
  return private.pc_before_battles(p_key,p_action,p_token,p_body);
 end if;
 if not exists(select 1 from private.petclass_config where key_hash=encode(extensions.digest(coalesce(p_key,''),'sha256'),'hex')) then raise exception '서버 인증 실패';end if;
 a:=private.pc_actor(p_token);cls:=(a->>'classId')::uuid;
 if a is null or cls is null or a->>'role' not in('student','teacher') then return jsonb_build_object('error','다시 로그인해 주세요.','status',401);end if;
 if not exists(select 1 from private.classes c join private.profiles p on p.id=c.teacher_id where c.id=cls and c.archived_at is null and p.approval_status='approved') then return jsonb_build_object('error','사용할 수 없는 학급입니다.','status',403);end if;
 if p_action='battleLobby' then return private.pc_battle_lobby(a);end if;
 if p_action='tournamentCreate' then
  if a->>'role'<>'teacher' then return jsonb_build_object('error','교사만 개최할 수 있어요.','status',403);end if;
  if coalesce(char_length(btrim(p_body->>'name')),0) not between 1 and 80 or coalesce(char_length(p_body->>'conditions'),0)>2000 or coalesce(char_length(btrim(p_body->>'prize')),0) not between 1 and 1000 or coalesce(p_body->>'petLimit','') not in('1','2','3') then raise exception '대회 입력값을 확인해 주세요.';end if;
  bid:=(p_body->>'requestId')::uuid;
  select * into existing from private.petclass_tournaments where id=bid;
  if found then
   if existing.class_id<>cls or existing.name<>btrim(p_body->>'name') or existing.conditions<>coalesce(p_body->>'conditions','') or existing.prize<>btrim(p_body->>'prize') or existing.pet_limit<>(p_body->>'petLimit')::int then raise exception '이미 사용한 요청 번호입니다.';end if;
  else
   insert into private.petclass_tournaments(id,class_id,name,conditions,pet_limit,prize) values(bid,cls,btrim(p_body->>'name'),coalesce(p_body->>'conditions',''),(p_body->>'petLimit')::int,btrim(p_body->>'prize'));
  end if;
  return private.pc_battle_lobby(a);
 end if;
 if a->>'role'<>'student' then return jsonb_build_object('error','학생만 배틀에 참여할 수 있어요.','status',403);end if;
 sid:=(a->>'id')::uuid;
 -- ponytail: one short class lock serializes starts; use ordered participant locks if classes grow beyond classroom size.
 if p_action='battleChallenge' then
  target:=(p_body->>'opponentId')::uuid;bid:=(p_body->>'requestId')::uuid;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(cls::text,0));
  select * into b from private.petclass_battles where id=bid;
  if found then
   if b.class_id<>cls or b.challenger<>sid or b.opponent<>target then raise exception '이미 사용한 요청 번호입니다.';end if;
   return private.pc_battle_lobby(a);
  end if;
  if target=sid or not exists(select 1 from public.classroom_students where id=target and class_id=cls and active) then raise exception '우리 반의 다른 학생을 선택해 주세요.';end if;
  if (select count(*) from private.petclass_farms where student_id in(sid,target) and jsonb_array_length(data->'pets')>0)<>2 then raise exception '두 학생 모두 펫이 필요해요.';end if;
  if exists(select 1 from private.petclass_battles where least(challenger,opponent)=least(sid,target) and greatest(challenger,opponent)=greatest(sid,target) and status in('pending','accepted','active')) then raise exception '이미 신청했거나 진행 중인 배틀이 있어요.';end if;
  insert into private.petclass_battles(id,class_id,challenger,opponent) values(bid,cls,sid,target);
  return private.pc_battle_lobby(a);
 end if;
 bid:=(p_body->>'battleId')::uuid;
 if p_action='battleCommit' then perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(cls::text,0));end if;
 select * into b from private.petclass_battles where id=bid and class_id=cls and sid in(challenger,opponent) for update;
 if not found then return jsonb_build_object('error','참여한 배틀을 찾을 수 없어요.','status',404);end if;
 if p_action='battleRespond' then
  if sid<>b.opponent then return jsonb_build_object('error','받은 학생만 응답할 수 있어요.','status',403);end if;
  if jsonb_typeof(p_body->'accept') is distinct from 'boolean' then raise exception '승인 여부를 확인해 주세요.';end if;
  if b.status='pending' then update private.petclass_battles set status=case when (p_body->>'accept')::boolean then 'accepted' else 'rejected' end,version=version+1,updated_at=now() where id=bid;
  elsif b.status<>(case when (p_body->>'accept')::boolean then 'accepted' else 'rejected' end) then raise exception '이미 응답한 배틀입니다.';end if;
  return private.pc_battle_lobby(a);
 end if;
 select * into r from private.petclass_battle_requests where actor_id=a->>'id' and request_id=(p_body->>'requestId')::uuid;
 if found then
  if r.fingerprint<>p_body->>'fingerprint' or r.battle_id<>bid then raise exception '이미 사용한 요청 번호입니다.';end if;
  return jsonb_build_object('replayed',true);
 end if;
 if p_action='battleContext' then
  return jsonb_build_object('actorId',sid,'battle',to_jsonb(b),'pets',jsonb_build_array(
    coalesce((select data->'pets' from private.petclass_farms where student_id=b.challenger),'[]'),
    coalesce((select data->'pets' from private.petclass_farms where student_id=b.opponent),'[]')));
 end if;
 if p_action='battleCommit' then
  if b.version<>(p_body->>'version')::int then return jsonb_build_object('error','다시 시도해 주세요.','status',409);end if;
  if p_body->>'status' not in('active','finished') or jsonb_typeof(p_body->'data') is distinct from 'object' then raise exception '전투 결과를 확인해 주세요.';end if;
  if b.status='accepted' and p_body->>'status'='active' and exists(select 1 from private.petclass_battles x where x.id<>bid and x.class_id=cls and x.status='active' and (x.challenger in(b.challenger,b.opponent) or x.opponent in(b.challenger,b.opponent))) then raise exception '둘 중 한 명이 다른 배틀을 진행 중이에요.';end if;
  update private.petclass_battles set data=p_body->'data',status=p_body->>'status',version=version+1,updated_at=now() where id=bid;
  insert into private.petclass_battle_requests values(a->>'id',(p_body->>'requestId')::uuid,p_body->>'fingerprint',bid);
  return jsonb_build_object('ok',true);
 end if;
 raise exception '지원하지 않는 배틀 작업입니다.';
end$$;
revoke all on private.petclass_battles,private.petclass_tournaments,private.petclass_battle_requests from public,anon,authenticated;
revoke all on function private.pc_battle_lobby(jsonb),private.pc_before_battles(text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.petclass_gateway(text,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.petclass_gateway(text,text,text,jsonb) to anon;

-- Include the new activity in existing administrator reset/export flows.
alter function private.pc_clear_class(uuid,boolean) rename to pc_clear_class_before_battles;
create function private.pc_clear_class(p_class uuid,p_all boolean) returns void language plpgsql security definer set search_path='' as $$
begin
 delete from private.petclass_battles where class_id=p_class;
 delete from private.petclass_tournaments where class_id=p_class;
 perform private.pc_clear_class_before_battles(p_class,p_all);
end$$;
alter function private.pc_export(uuid) rename to pc_export_before_battles;
create function private.pc_export(p_class uuid) returns jsonb language sql security definer set search_path='' as $$
 select private.pc_export_before_battles(p_class)||jsonb_build_object(
 'battles',coalesce((select jsonb_agg(to_jsonb(b)) from private.petclass_battles b where class_id=p_class),'[]'),
 'tournaments',coalesce((select jsonb_agg(to_jsonb(t)) from private.petclass_tournaments t where class_id=p_class),'[]'));
$$;
revoke all on function private.pc_clear_class(uuid,boolean),private.pc_export(uuid),private.pc_clear_class_before_battles(uuid,boolean),private.pc_export_before_battles(uuid) from public,anon,authenticated;
